#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers

sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get update -y
sudo apt-get install -y haproxy

echo -e \
	"
frontend localnodes
	bind *:80
	mode http
	default_backend nodes
backend nodes
\tmode http
\tbalance roundrobin
\tserver 68558-web-01 52.72.27.194
\tserver 68558-web-02 52.201.158.148" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
