#!/usr/bin/env bash
# Print Hi when loop reaches the 9th iteration else Bestschool
i=1 
while (("$i" <= 10))
do
    echo "Best School"
    if (("$i" == 9))
     then
        echo "Hi"
    fi
        ((i++))
done