#!/usr/bin/env bash

i=1 
while (("$i" <= 10))
do
    if (("$i" == 4))
     then
        echo "Bad luck"
    elif (("$i" == 8))
     then
        echo "Good luck"
    else
        echo "Best School"
    fi
        ((i++))
done