#!/usr/bin/env bash
t="./school"
if [ -e "$t" ]
    then
        echo "school file exists"
        if [ -s "$t" ]
            then echo "school file is not empty"
        else
            echo "school file is empty"
        fi
        if [ -f "$t" ]
            then
                echo "school file is a regular file"
        fi
else
        echo "school file does not exist"
fi