#!/usr/bin/env bash
# Checking the user
useradd nginx
sudo sed -i 's/user .*/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
